name: PHP CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        php-version: ['7.4']

    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@2.9.0
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: "Install PHPUnit"
        run: composer require phpunit/phpunit

      - name: Run test suite
        run: composer run-script test
